version:  '3'

services:
  nginx:
    env_file: .env
    build: ./requirements/nginx
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    restart: always
    ports:
      - 443:443

  wordpress:
    env_file: .env
    build: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    restart: always

  mariadb:
    env_file: .env
    build: ./requirements/wordpress
    # TODO: should check /var/run/mysqld or /var/lib/mysql which one is correct
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always

volumes:
  db_data:
    driver: local
    driver_opts:
      device: /home/soulee/data/www
      o: bind
  wp_data:
    driver: local
    driver_opts:
      device: /home/soulee/wp-/mysql

networks:
  inception:
    driver: bridge
