version:  '3'

services:
  mariadb:
    env_file: .env
    build: ./requirements/mariadb
    volumes:
      - db-v:/var/run/mysqld
    networks:
      - inception
    restart: always

  wordpress:
    env_file: .env
    build: ./requirements/wordpress
    volumes:
      - www-v:/var/www
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

  nginx:
    env_file: .env
    build: ./requirements/nginx
    volumes:
      - www-v:/var/www
    networks:
      - inception
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress

volumes:
  db-v:
    driver: local
    driver_opts:
      device: /home/soulee/data/db
      type: none
      o: bind
  www-v:
    driver: local
    driver_opts:
      device: /home/soulee/data/wordpress
      type: none
      o: bind

networks:
  inception:
    driver: bridge
